Add cond operation for conditional selection
BasisResearch/chirho pull request #141
Opened 2023-06-09 13:19 UTC by eb8680

Extracted from #135. ~~Blocked by #140.~~

2023-07-13 03:41 UTC, SamWitty commented
@rfl-urbaniak , are you able to review this PR or would you like me to once I'm back from the ASKEM hackathon?

2023-07-13 13:51 UTC, rfl-urbaniak commented
I mistakenly assumed Eli added me just to keep me in the loop - will get on it first thing tomorrow morning (CET)!

2023-07-14 07:09 UTC, rfl-urbaniak requested changes
Just a nit related to type hinting.

2023-07-14 14:45 UTC, rfl-urbaniak approved these changes

2023-07-14 14:57 UTC, merged