WIP - Decouple ODE
BasisResearch/chirho pull request #290
Opened 2023-09-22 23:34 UTC by SamWitty

2023-09-24 02:59 UTC, eb8680 commented
There are a bunch of merge conflicts to resolve following #286.

2023-09-24 04:02 UTC, SamWitty commented
Strange that there are all of these merge conflicts, as `sw-decouple-ODE` directly branched off of the `sw-dynamics-refactor-2` branch that was used in #286 . I suspect this is something to do with GitHub not recognizing squash-and-merge behavior? Maybe something else? Either way, I'll resolve by accepting all from `sw-decouple-ODE`.

2023-09-26 14:19 UTC, agrawalraj commented on chirho/dynamical/internals/ODE/backends/torchdiffeq.py
> +
Code below is new; code above is old

2023-09-26 14:21 UTC, agrawalraj commented on chirho/dynamical/internals/ODE/backends/torchdiffeq.py
> +@ode_simulate.register(TorchDiffEq)
This is the key functionality / small indirection from before

2023-09-26 14:23 UTC, agrawalraj commented on chirho/dynamical/ops/ODE/backends/torchdiffeq.py
> +class TorchDiffEq(ODEBackend):
This is a class so we can dispatch on it

2023-09-26 15:05 UTC, agrawalraj requested changes
Could you also run the notebook to make sure the the inferences still make sense?

2023-09-26 15:06 UTC, agrawalraj commented
Otherwise, everything looks really great @SamWitty!

2023-09-26 18:37 UTC, agrawalraj approved these changes
Looks great!

2023-09-26 18:38 UTC, merged