Reproduce DR learner notebook using `chirho.robust`
BasisResearch/chirho pull request #474
Opened 2024-01-03 00:20 UTC by agrawalraj

This PR closes https://github.com/BasisResearch/chirho/issues/372, https://github.com/BasisResearch/chirho/issues/373

2024-01-12 15:44 UTC, eb8680 commented
Needs merge conflict resolution following merge of #398 to `master`

2024-07-16 15:13 UTC, SamWitty requested changes
This notebook could certainly use some more text, but I think we can add that in a subsequent PR. 

See my comment about the outline for an easy to address issue that should be fixed before the PR lands.

2024-07-16 15:13 UTC, SamWitty commented on docs/source/automated_dr_learner.ipynb
I believe the outline is taken from the backdoor adjustment tutorial, and doesn't align with this notebook.

2024-07-18 00:39 UTC, eb8680 commented on docs/source/automated_dr_learner.ipynb
I think the outlines are wrong or at least have broken links in a number of other tutorials, which suggests the manually written outlines may be too brittle to bother maintaining when Sphinx, JupyterLab, VSCode and most other editors already generate and render outlines automatically from the section headers. I just removed it from this one entirely.

2024-07-18 13:13 UTC, SamWitty commented on docs/source/automated_dr_learner.ipynb
Sounds good. We can follow up in a separate PR to make all the outlines consistent with whatever we decide.

2024-07-18 13:14 UTC, SamWitty approved these changes

2024-07-18 13:14 UTC, merged