Multilevel model tutorial with dynamical systems
BasisResearch/chirho pull request #542
Opened 2024-05-01 13:50 UTC by SamWitty

Subsumes #351 .

Still need to add text, but the analysis is basically there.

2024-08-12 21:34 UTC, djinnome commented on docs/source/dynamical_multi.ipynb
In this notebook, you say:

```python
# Assume there is initially a population of 99 million people that are susceptible, 1 million infected, and 0 recovered
```
However, since this is a multilevel model, each strata gets 99 million susceptible and 1 million infected, so all together, it should be 297 million people susceptible and 3 million infected, divided equally among all 3 strata.

2024-08-12 21:41 UTC, djinnome commented on docs/source/dynamical_multi.ipynb
When initializing the cadence of observations, you say:

```python
obs_sample_rate = torch.tensor(1/7) # Take measurements one per week
```

However, since the timescale is months, not days, it should be 

```python
obs_sample_rate = torch.tensor(1/4) # Take measurements one per week
```

If you meant for the timestep to be days, then it should be:

```python
obs_sample_rate = torch.tensor(7.0) # Take measurements one per week
```

2024-11-06 00:05 UTC, djinnome commented
Why is `sir_observation_model` a recursive function?

2024-11-06 00:12 UTC, djinnome commented on docs/source/dynamical_multi.ipynb
It looks like the `obs_sample_rate` is still 1/7, not 1/4.

2024-11-06 00:16 UTC, djinnome commented
In `bayesian_multilevel_sir_prior` the variable called `plate` should be called `strata`

2025-01-23 21:17 UTC, djinnome commented on docs/source/dynamical_multi.ipynb
The prior marginal and conditional distributions of the parameters should be a different color for each town. Currently, they are all the same color.  This could be fixed by introducing:

```python
town_colors = ["cyan", "magenta", "chartreuse"]
...
for i in range(3):
    sns.kdeplot(
        parameter_prior_samples['beta'][:, i],
        ax=ax[1,0],
        alpha=0.4,
        color=town_colors[i],
        label=f"Town {i} $\\beta$ - Marginal Probability",
        linewidth=1.5,
        bw_adjust=.6,
        clip=(0, 1),
    )
```

2025-01-23 21:19 UTC, djinnome requested changes
Just a couple minor plotting issues, but otherwise, it looks ready to go.

2025-01-23 21:19 UTC, djinnome commented on docs/source/dynamical_multi.ipynb
Since time is measured in units of months, a weekly `obs_sample` rate should be 1/4, not 1/7.

2025-03-18 13:03 UTC, SamWitty commented on docs/source/dynamical_multi.ipynb
Thank you for the comment, but I disagree.

2025-03-18 13:12 UTC, eb8680 approved these changes
Looks good, no issues that should block merging

2025-03-18 13:15 UTC, merged